### ISSUE TITLE
deployment target is 9.1

### ISSUE THREAD

**Issue by Nef10** [dennisweissmann/DeviceKit#10]
```Module file's minimum deployment target is ios9.1 v9.1: /Carthage/Build/iOS/DeviceKit.framework/Modules/DeviceKit.swiftmodule/arm64.swiftmodule```

Could you change the deployment target to 8.0 as indicated in the README, so someone could use the Carthage version for projects which should support iOS version before 9.1?
Thanks!

**Comment by dennisweissmann** [comment]
🙊 Sorry for this! Thanks for reporting! I've just published a new release (0.1.1). Could you verify that it's working for you? Thanks! :)

**Comment by Nef10** [comment]
Works for me :+1: , thanks for the quick fix

**Comment by dennisweissmann** [comment]
Perfect! :) thanks for using it :)
