### ISSUE TITLE
Carthage build still not working with version 1.3.3

### ISSUE THREAD

**Issue by nmDejamobile** [dennisweissmann/DeviceKit#100]
Hi, here is the log from `carthage update DeviceKit --platform ios --cache-builds`

> *** Checking out DeviceKit at "1.3.3"
> *** xcodebuild output can be found in [/var/folders/9w/ng8hkhns2lb5hqdcw85vm5kc0000gn/T/carthage-xcodebuild.b8QBr5.log](https://github.com/dennisweissmann/DeviceKit/files/1322098/carthage-xcodebuild.b8QBr5.txt)
> *** Invalid cache found for DeviceKit, rebuilding with all downstream dependencies
> *** Building scheme "DeviceKit" in DeviceKit.xcodeproj
> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -project /Users/[myuser]/[myproject]
> 
> /Carthage/Checkouts/DeviceKit/DeviceKit.xcodeproj -scheme DeviceKit -configuration Release -derivedDataPath /Users/[myuser]/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/DeviceKit/1.3.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/[myuser]/[myproject]/Carthage/Checkouts/DeviceKit)
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: [/var/folders/9w/ng8hkhns2lb5hqdcw85vm5kc0000gn/T/carthage-xcodebuild.b8QBr5.log](https://github.com/dennisweissmann/DeviceKit/files/1322098/carthage-xcodebuild.b8QBr5.txt)
> 

I reverted to 1.2.3 for the moment.

**Comment by dennisweissmann** [comment]
Hm, you're using Xcode 8.3.3 which we don't officially support anymore, > 1.3.0 requires Swift 4 (even though it should work with Xcode 8.3.3 except that the flag in the build settings is set to Swift4 instead of Swift 3 🤔 Can you upgrade to Xcode 9 or is there anything preventing you from that?

**Comment by nmDejamobile** [comment]
@dennisweissmann Ok, thanks. I'll will update as soon as my current project leaves me some time to.

**Comment by dennisweissmann** [comment]
Thank you :) and sorry for the trouble
