### ISSUE TITLE
Carthage update issue with XCode 9

### ISSUE THREAD

**Issue by brandFromNSK** [dennisweissmann/DeviceKit#104]
Hi!

Got an issue

> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -project /Users/Andrey/MFO_BOX/Carthage/Checkouts/DeviceKit/DeviceKit.xcodeproj -scheme DeviceKit -configuration Release -derivedDataPath /Users/Andrey/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.3_8E3004b/DeviceKit/1.3.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/Andrey/MFO_BOX/Carthage/Checkouts/DeviceKit)
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/4j/220h75g17k32pn1_6t59tc8w0000gp/T/carthage-xcodebuild.ySawYr.log

I have 2 XCode versions on machine: 8.3.3 and 9 GM. It happened when I tried to update carthage with DeviceKit v. 1.4.0 at Cartfile. Downgrate to v. 1.2.3 only help me, but I need to get support for new devices

**Comment by dennisweissmann** [comment]
Sorry for the trouble :(

Can you make sure that you command line tools point to Xcode 9?
This is usually


> xcode-select --switch /Applications/Xcode.app

(replace Xcode.app with the name of your Xcode 9 instance)

**Comment by dennisweissmann** [comment]
@brandFromNSK Can I close this or is this still an issue?

**Comment by brandFromNSK** [comment]
Yes, when I upgrated my XCode version to last and selected actual XCode app with command line issue is done! Thanks!
