### ISSUE TITLE
Device.allPhonesIncludingSimulators

### ISSUE THREAD

**Issue by bikisDesign** [dennisweissmann/DeviceKit#105]
If theres an allPhones option it seems silly to have to add in a bunch of extras in order to support simulators.  Adding an additional static var for simulators would be super helpful for me as i use these all over my project for UI layout.

**Comment by dennisweissmann** [comment]
There’s also an `allSimulatorPhones` property which you can use (or add the two arrays `let reallyAllPhones = Device.allPhones + Device.allSimulatorPhones` should give you what you need.
