### ISSUE TITLE
Machine String / Identifier

### ISSUE THREAD

**Issue by ehmjaysee** [dennisweissmann/DeviceKit#114]
Add a property field to return the "machine string" for the device. i.e. "iPhone9,1" for iPhone 7.  This would be useful for the case where the code is running on a newer platform that is not yet recognized by DeviceKit.

**Comment by dennisweissmann** [comment]
IIUC you are looking for the associated value in the `.unknown` case.

Assume there is no iPhone10,1 support in DeviceKit and you're running on such a phone,

```
switch device {
case let .unknown(identifier): print(identifier)
default: break
}
```
would give you what you want right?

**Comment by ehmjaysee** [comment]
Looking closer at the code it seems the code is already designed to return the identifier property if the platform type is unknown. Also I found I could access the platform identifier value directly this way: Device.identifier so I will close this.
