### ISSUE TITLE
Does not recognise real iPhone X device 

### ISSUE THREAD

**Issue by MehdiMahdloo** [dennisweissmann/DeviceKit#115]
The library has a problem to recognise a true iPhone X.

iPhone X has two device identifiers, which are 10,3 and 10,6.

The library only recognise the 10,3 identifier and not the 10,6.

Please fix :)

Thank you ❤️

**Comment by dennisweissmann** [comment]
Solved via Twitter DM; the problem was that OP aided an old version (1.3.2).

**Comment by iOSDias** [comment]
let group58: [Device] = [.iPhoneX, .simulator(.iPhoneX)]
 if device.isOneOf(group58) {
            Constants.fontSize = 19
}

I use this fontSize in all my labels, etc. 
In Simulator of iPhoneX app is showing normally, but in real it is not
![whatsapp image 2018-04-04 at 20 36 19](https://user-images.githubusercontent.com/31696378/38317583-2e37d058-384f-11e8-8384-945ab618342d.jpeg)
![Uploading WhatsApp Image 2018-04-04 at 20.36.18.jpeg…]()

**Comment by dennisweissmann** [comment]
@iOSDias That's unfortunate, I'm sorry for that! However, I don't have an iPhone X to test this, can you tell me the identifier of your iPhone X? (i.e. `Device().identifier`) Thanks!
