### ISSUE TITLE
Getting the real model of the device, if simulator

### ISSUE THREAD

**Issue by phimage** [dennisweissmann/DeviceKit#129]
I make this extension, to return the underlying device, if the device is a simulator

```swift
extension Device {

    /// If this device is a simulator return the underlying device,
    /// otherwise return `self`.
    public var underlying: Device {
        if case .simulator(let model) = self {
            return model
        }
        return self
    }

}
```

I call it `underlying`, but before PR I am wondering if you have a better name.

**Comment by dennisweissmann** [comment]
Hm, we could make it more "generic" and provide it as a function like `realDevice(from device: Device) -> Device` where if `device` is a simulator it returns the corresponding device, or if it's not a simulator just the `device`. WDYT?

**Comment by phimage** [comment]
the word "real" is used in framework so good point to use it

it could be real
`public var real: Device {`

or as you say a function (no preference)
```swift
extension Device {

    /// Get the real device from a device.
    ///
    /// - parameter device: A device.
    ///
    /// - returns: the underlying device If the `device` is a `simulator`,
    /// otherwise return the `device`.
    public static func realDevice(from device: Device) -> Device {
        if case .simulator(let model) = device {
            return model
        }
        return device
    }

}
```

**Comment by dennisweissmann** [comment]
Thanks for your contribution @phimage ! :) I have added it in cf28f798f045eae084040dfb4531c92e957f0e48
