### ISSUE TITLE
UserInterfaceIdiom CarPlay problem

### ISSUE THREAD

**Issue by ardaerzin** [dennisweissmann/DeviceKit#13]
The current pod version is not building for me, saying:

    Enum case 'CarPlay' not found in type 'UIUserInterfaceIdiom'

I couldn't find anything about the CarPlay enum in the apple docs for UIUserInterfaceIdiom

**Comment by dennisweissmann** [comment]
Do you link against iOS 9.3? If you are still using Xcode 7.2 you're not and you need to use the 0.3.0 version :( I probably should put that in the readme.

**Comment by ardaerzin** [comment]
@dennisweissmann yea I noticed your commits after I opened the issue, but It wasn't very clear at the beginning. sometimes cocoapods updates are just way too easy and cause this kinda problems. 0.3.0 is working without any problems.

**Comment by dennisweissmann** [comment]
Okay, I'm sorry for the trouble :( I changed the readme to make that more explicit. I'll close this for now, okay?

**Comment by ardaerzin** [comment]
Sure, I didn't do it in case you wanted to keep as a ref or anything.
