### ISSUE TITLE
Feature request: >, ==, < operators

### ISSUE THREAD

**Issue by pasevin** [dennisweissmann/DeviceKit#132]
Would be very useful to have a way to do something like this:

```
if device > .iPhone6 {
}
```

**Comment by dennisweissmann** [comment]
We would need to define semantics for that.

What does it mean? Newer? Better? Larger? 

If it’s one of the first two: how do we handle devices with the same stats (e.g. same processor / ram but came out later, e.g. SE devices) ... Any ideas?

**Comment by pasevin** [comment]
Good points. I was thinking just in pure chronological terms. Meaning iPhone5s < iPhone6 < iPhone6s < iPhoneSE ... based on this 
![image](https://user-images.githubusercontent.com/1058469/40937771-8c403af8-67f4-11e8-8018-a2a1f80c9257.png)

But now I can see how this can be confusing.

One solution for this could be:

```
if device.releaseDate > .iPhoneSE(property: .releaseDate) { ... }
```

Then we could have more options like this:

```
if device.screenSize > .iPhoneSE(property: .screenSize) { ... }
```

**Comment by ShivaHuang** [comment]
I'm wondering, if you are going to compare the same property of two devices, say the `screenSize` in your example, why not just compare it like this:

```swift
if device.screenSize > .iPhoneSE.screenSize { ... }
```

the only problems are:

1. We don't have the property `screenSize` now.
2. The `CGSize`, assuming `screenSize` is `CGSize`, doesn't conform to `Comparable`. You need to define your own rule for this.

**Comment by dennisweissmann** [comment]
I agree with Shiva here, you don’t compare devices at their whole but single properties. If you want to introduce single properties (like release date, total RAM available, etc.) I’m very open to this :)
