### ISSUE TITLE
Enum case 'CarPlay' not found in type 'UIUserInterfaceIdiom'

### ISSUE THREAD

**Issue by ITGypsy** [dennisweissmann/DeviceKit#14]
Got this error after upgrading to the newest version.

El Capitan 10.11.1
Xcode 7.2.1 (7C1002)
DeviceKit 0.3.1
CocoaPods 0.39.0

**Comment by dennisweissmann** [comment]
Sorry for the inconvenience!

In the readme I tried to clarify that

> Version 0.3.1 requires Xcode 7.3 because it contains a fix for the UIUserInterfaceIdiom wrapper enum that would not build otherwise (specifically you need to link against the iOS 9.3 SDK). If you still use Xcode 7.2.1 or lower (and do not link against the latest SDK) please use version 0.3.0.

I'll try to find a better solution as this question already arose in an earlier issue #13.

However, thanks for reporting and thanks for using the code :)

**Comment by ITGypsy** [comment]
Gotcha, thanks. :)

**Comment by dennisweissmann** [comment]
You're welcome :)

**Comment by tomlokhorst** [comment]
Just ran into this as well.

For the future:
You can release this as 0.3.1.beta, that way CocoaPods won't automatically update to this version, unless you explicitly ask for the beta. That way you can already release features that only apply to beta SDKs versions.

Btw, thanks for DeviceKit, it's a useful library!

**Comment by dennisweissmann** [comment]
Thanks for the tip! I'll definitely do that! Glad you like it :)
