### ISSUE TITLE
Error: UIAccessibilityIsGuidedAccessEnabled()

### ISSUE THREAD

**Issue by denisenepraunig** [dennisweissmann/DeviceKit#141]
Hello Dennis,

when I use your pod in Xcode Version 10.0 beta 6 (10L232m) with Swift 4 and I get the following error for Device.generated.swift:

```'UIAccessibilityIsGuidedAccessEnabled()' has been replaced by property 'UIAccessibility.isGuidedAccessEnabled'```

Best Regards,
Denise

**Comment by denisenepraunig** [comment]
My Podfile:

```
target 'ota-pod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ota-pod
  pod 'DeviceKit', '~> 1.3'

end
```

**Comment by dennisweissmann** [comment]
Hi namesake :)

Thanks for using DeviceKit :)

Please update to a newer version of DeviceKit, for beta versions - as in your case - please use the latest master)

in your podfile:

pod 'DeviceKit', :git => 'https://github.com/dennisweissmann/DeviceKit.git', :branch => 'master'

I'll make this clearer in the readme, thanks :)

**Comment by denisenepraunig** [comment]
Thank you, namesake :) Worked like a charm! 👌
