### ISSUE TITLE
[Solved] Miss iPhone XR, XS and XS Max?

### ISSUE THREAD

**Issue by oTranAnhMinh** [dennisweissmann/DeviceKit#143]
Hello,

Do you have any update detected for phone XR, XS and XS MAX? 

Thanks,

**Comment by oTranAnhMinh** [comment]
Thank you so much @dennisweissmann

**Comment by NaturalLam** [comment]
Thanks @dennisweissmann , when would that be push to a release version?

**Comment by dennisweissmann** [comment]
@NaturalLam I'm currently in the process of releasing a new version (1.8.0), once https://travis-ci.org/dennisweissmann/DeviceKit/builds/429446526 is done it should be released automatically :)

**Comment by dennisweissmann** [comment]
Released :)
