### ISSUE TITLE
Task failed with exit code 65

### ISSUE THREAD

**Issue by qunwang6** [dennisweissmann/DeviceKit#145]
carthage update
*** Fetching DeviceKit
*** Checking out DeviceKit at "1.8.0"
*** xcodebuild output can be found in /var/folders/3b/fnjwh2qj5y9gj9p9pyvxvlkw0000gn/T/carthage-xcodebuild.vjjvxL.log
*** Building scheme "DeviceKit" in DeviceKit.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Apple/Documents/App/BookPlayer/BookPlayer2/Carthage/Checkouts/DeviceKit/DeviceKit.xcworkspace -scheme DeviceKit -configuration Release -derivedDataPath /Users/Apple/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/DeviceKit/1.8.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/3b/fnjwh2qj5y9gj9p9pyvxvlkw0000gn/T/DeviceKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Apple/Documents/App/BookPlayer/BookPlayer2/Carthage/Checkouts/DeviceKit)

**Comment by dennisweissmann** [comment]
can you please add that log /var/folders/3b/fnjwh2qj5y9gj9p9pyvxvlkw0000gn/T/carthage-xcodebuild.vjjvxL.log to the report? Are you using Xcode 10?

**Comment by anasstalii** [comment]
Then I see for xcode 10/swift 4.2 this task #141
An if on swift version could allow to support xcode 9/swift 4.1 also

**Comment by phimage** [comment]
This last comment was me. I was on another mac with Xcode 9.4 to test (and do not see that someone else is connected on github)

**Comment by dennisweissmann** [comment]
Hi @phimage, that's true, this would be a better solution ... working on it :)

**Comment by qunwang6** [comment]
solved
change `github "dennisweissmann/DeviceKit" ~> 1.7` to `github "dennisweissmann/DeviceKit" ~> 1.3`
thanks.
