### ISSUE TITLE
Carthage cache issue (testing with 1.8)

### ISSUE THREAD

**Issue by phimage** [dennisweissmann/DeviceKit#146]
Do not know if it is an Xcode 10 or carthage issue or DeviceKit scheme
When I build, cache is never used.

So just wondering if it is an issue with `DeviceKit` 1.8 because I have a lot of frameworks without any issue
```bash
xcodebuild output can be found in /Users/emarchand/perforce/ericm/depot/4eDimension/main/QMobile/QMobileDataSync/build/log
*** Valid cache found for Alamofire, skipping build
*** Invalid cache found for DeviceKit, rebuilding with all downstream dependencies
*** Valid cache found for FileKit, skipping build
*** Valid cache found for Prephirences, skipping build
*** Valid cache found for Result, skipping build
*** Valid cache found for BrightFutures, skipping build
*** Valid cache found for Moya, skipping build
*** Valid cache found for SwiftyJSON, skipping build
*** Valid cache found for XCGLogger, skipping build
```
Maybe because the code is generated and there is some hash checking, different with xcode 10

I check an old build in my Continous integration
```
Step 7/17] *** Valid cache found for DeviceKit, skipping build
````

---

```bash
$ carthage version
0.30.1
```
```bash
$ cat Cartfile
github "dennisweissmann/DeviceKit"
```

```bash
$ carthage update --platform iOS --cache-builds
*** Fetching DeviceKit
*** Checking out DeviceKit at "1.8.0"
*** xcodebuild output can be found in /var/folders/4s/whlygvvx3sqfq77vq3slrp7r0000gq/T/carthage-xcodebuild.A8lFMr.log
*** Invalid cache found for DeviceKit, rebuilding with all downstream dependencies
*** Building scheme "DeviceKit" in DeviceKit.xcworkspace
$
$ carthage update --platform iOS --cache-builds
*** Fetching DeviceKit
*** Checking out DeviceKit at "1.8.0"
*** xcodebuild output can be found in /var/folders/4s/whlygvvx3sqfq77vq3slrp7r0000gq/T/carthage-xcodebuild.HHcaUx.log
*** Invalid cache found for DeviceKit, rebuilding with all downstream dependencies
```

I remove my carthage cache and derived data.

---

The build work fine anyway
```bash
$ cat /var/folders/4s/whlygvvx3sqfq77vq3slrp7r0000gq/T/carthage-xcodebuild.HHcaUx.log | xcpretty
▸ Processing Info.plist
▸ Running script 'Generate Device'
▸ Compiling DeviceKit_vers.c
▸ Compiling DeviceKit_vers.c
▸ Compiling Device.generated.swift
▸ Compiling Device.generated.swift
▸ Analyzing DeviceKit_vers.c
▸ Linking DeviceKit
▸ Linking DeviceKit
▸ Generating 'DeviceKit.framework.dSYM'
▸ Touching DeviceKit.framework (in target: DeviceKit)
▸ Archive Succeeded
▸ Processing Info.plist
▸ Running script 'Generate Device'
▸ Compiling Device.generated.swift
▸ Compiling Device.generated.swift
▸ Touching DeviceKit.framework (in target: DeviceKit)
▸ Generating 'DeviceKit.framework.dSYM'
▸ Build Succeeded
```

**Comment by phimage** [comment]
With some debug of carthage I see that in there is no header file in 
Carthage/Build/iOS/DeviceKit.framework
the header file is used to get the swift version used to compile the framework and to check with current.

**Comment by phimage** [comment]
So the one generated for objc compatibility, named xxx-Swift.h is used to read
`// Generated by Apple Swift version 4.2 effective-3.4 (swiftlang-1000.11.37.1 clang-1000.11.45.1)`

Maybe this is the project configuration to change. Name is not specified here, empty.
<img width="658" alt="screenshot 2018-09-19 at 08 22 25" src="https://user-images.githubusercontent.com/8875768/45734633-76cf4480-bbe5-11e8-9ebd-81732d954e54.png">

Value could be inherited from project if not defined, if we see upper level we have `$(SWIFT_MODULE_NAME)-Swift.h`

**Comment by dennisweissmann** [comment]
Hm, okay, I'll add it back then, thank you so much for investigating this!

**Comment by rzulkoski** [comment]
Thanks Dennis, when do you plan to release this change?

**Comment by igorkulman** [comment]
Any news about this?

**Comment by phimage** [comment]
@igorkulman I make the PR ;)
