### ISSUE TITLE
Conversion to Swift 4.2 is available

### ISSUE THREAD

**Issue by flexaddicted** [dennisweissmann/DeviceKit#148]
I'm running the latest Xcode Version 10.0 (10A255) and I'm using DeviceKit 1.8.1. 

Podfile.lock

```
- DeviceKit (1.8.1)
```

The Swift language version is 4.2.

Xcode continues to tell me I should update it:

![schermata 2018-09-20 alle 12 20 02](https://user-images.githubusercontent.com/1482350/45812392-f9343300-bccf-11e8-9e3f-e841f4b337f3.png)

Any idea?

**Comment by dennisweissmann** [comment]
Hi @flexaddicted , thanks for reporting this, I will look into it!

**Comment by phimage** [comment]
I see two `SWIFT_VERSION = 4.0;` and two `SWIFT_VERSION = 4.2;` in the project file

Could we set all to 4.2?

ps: 4.0 is in general Project and the test target

**Comment by dennisweissmann** [comment]
We should yes. I'll do that now and try to release a new version with your other change :) Thanks so much for working on that!

**Comment by dennisweissmann** [comment]
This should be fixed with 53a1b35a58b9f084795a1a05dff47a8d14aa5698
