### ISSUE TITLE
Getting diagonal -1.0 when device is simulator iPhone XR

### ISSUE THREAD

**Issue by Elipasousa** [dennisweissmann/DeviceKit#150]
When I try to get the diagonal from an iPhone XR (running iOS 12.0) simulator, I'm getting -1.0

Using version 1.8.1 of DeviceKit on Xcode 10.0 . I tried on iPhone 6S physical phone and on iPhone 6s simulator and there's no such problem.

Thanks

**Comment by Elipasousa** [comment]
Resetting the simulator fixed! Sorry

**Comment by dennisweissmann** [comment]
Perfect! Glad you found a solution because it would have had no idea why that happened 😱
