### ISSUE TITLE
iPhone XS, XS Max and Xr?

### ISSUE THREAD

**Issue by NoahJApps** [dennisweissmann/DeviceKit#152]
are the support for these going to be added?

**Comment by giacgbj** [comment]
Have you read the ticket (#143) and/or the release notes (https://github.com/dennisweissmann/DeviceKit/releases)?

**Comment by dennisweissmann** [comment]
Thanks for helping me out here @giacgbj! :) @NoahJApps If you use 1.8.1 or newer these devices are supported :)
