### ISSUE TITLE
Please explain the steps to take to add DeviceKit to your project after downloading with git?

### ISSUE THREAD

**Issue by ToddHoff** [dennisweissmann/DeviceKit#155]
I'm not sure how use DeviceKit after downloading it with git. Some added doc on how to integrate it would be great.

thanks

**Comment by dennisweissmann** [comment]
Hi Todd,

I think everything you need is already in the readme:

Installation (how to integrate it into your project)
https://github.com/dennisweissmann/DeviceKit/blob/master/README.md#installation

Usage (how to import the framework and use the enum):
https://github.com/dennisweissmann/DeviceKit/blob/master/README.md#usage

If something is still unclear, can you please elaborate on what it is, I'll be more than happy to add more details if needed to the readme!

thanks for using DeviceKit :)

- Dennis
