### ISSUE TITLE
1.10.0 runtime issue

### ISSUE THREAD

**Issue by walsht** [dennisweissmann/DeviceKit#157]
Showing Recent Messages
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in DeviceKit(Device.generated.o)
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dennisweissmann** [comment]
Hey @walsht , sorry for that :( do you have more information on this? I cannot reproduce this ...

**Comment by walsht** [comment]
I am using Carthage, and haven't upgraded to Swift 4.  Does that help?

**Comment by dennisweissmann** [comment]
huh, if you haven't upgraded to Swift you should use versions ≥ 1.0 < 1.3 only as per the compatibility table in the readme: https://github.com/dennisweissmann/DeviceKit

IIRC starting with Swift 4 you can mix the versions of Swift used with different libraries.

**Comment by walsht** [comment]
Ok.  1.9.0 works fine, so something in 1.10.0 changed to cause this issue.

**Comment by walsht** [comment]
@dennisweissmann Just moved to Swift 4.2 and having the same issue
```
Undefined symbols for architecture x86_64:
  "___llvm_profile_runtime", referenced from:
      ___llvm_profile_runtime_user in DeviceKit(Device.generated.o)
     (maybe you meant: ___llvm_profile_runtime_user)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by walsht** [comment]
I found the issue. https://github.com/Swinject/Swinject/issues/296#issuecomment-439661602
We use Carthage building creating static libraries.  Can you disable Code coverage?

**Comment by walsht** [comment]
@dennisweissmann I found a solution here: https://github.com/SwiftScream/URITemplate/issues/21#issuecomment-409893981

You can close this issue.

**Comment by dennisweissmann** [comment]
Glad you found a solution! Thanks for linking it! :)
