### ISSUE TITLE
Support for zoomed displays

### ISSUE THREAD

**Issue by jackchmbrln** [dennisweissmann/DeviceKit#29]
When dealing with interfaces for different device sizes I would like to know what scale the user is using for the display i.e. Standard or Zoomed

Because the zoomed display on an iPhone 6 has the same resolution as an iPhone 5 the interface will not layout correctly.

It would be useful to something such as:

`let Device  = Device()`
` if device.isZoomed {}`

Thanks!

**Comment by dennisweissmann** [comment]
Hey @jackchmbrln, thanks for filing! Do you any public API that provides this knowledge? I couldn't find anything (in my very shallow research).

**Comment by jackchmbrln** [comment]
Hi Dennis,  

Thanks for the reply, I do know of one way of doing it, whether thaf fits into your framework or not.  

You can do  

UIScreen.mainScreen().scale < UIScreen.mainScreen().nativeScale  

I'm on my iPhone so can't remember the exact syntax but it's along those lines.  

Hope it helps,  
Jack

Jack Chamberlain  
Off Piste / iOS Brewer
07852746399(tel:07852746399)
jack.chamberlain97@gmail.com




J

**Comment by dennisweissmann** [comment]
Indeed that helps! Awesome! Once I have all my exams finished I'll implement it! Thank you! :)

**Comment by jackchmbrln** [comment]
Cool, glad I could help. Good luck with the exams!

Jack Chamberlain
Off Piste / iOS Brewer
*07852746399*

*jack.chamberlain97@gmail.com <jack.chamberlain97@gmail.com>*

J

On 7 July 2016 at 20:42:36, Dennis Weissmann (notifications@github.com)
wrote:

Indeed that helps! Awesome! Once I have all my exams finished I'll
implement it! Thank you! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dennisweissmann/DeviceKit/issues/29#issuecomment-231185696>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJmQIsVoiNHHSv3VMotgTH8k1Kij3twWks5qTVargaJpZM4JG2lR>
.

**Comment by dennisweissmann** [comment]
This is resolved in 6ad2b4f0f1d45d8bbee843193c71fc201156ad6b and is available in the Swift 3 branch which will get merged to master as soon as Swift 3 is out of beta :) Thanks again @jackchmbrln!
