### ISSUE TITLE
enum for iPad Pro size?

### ISSUE THREAD

**Issue by mtissington** [dennisweissmann/DeviceKit#35]
I looked at the code but didn't see anything to differentiate between iPad Pro size.

How do we do this?

**Comment by dennisweissmann** [comment]
Good question! I thought we already covered this. I'll work on a fix as soon as possible but it might take week :( Thanks for raising the issue! 🙏

Note to self: https://www.theiphonewiki.com/wiki/Models

**Comment by Urkman** [comment]
I created a Pull Request for that...

**Comment by Urkman** [comment]
Could you create a new version, that makes it easier to install using Cocoapods?

**Comment by dennisweissmann** [comment]
Already at it :) It always takes some time (somehow I always screw up my ruby versions and cannot run CocoaPods ...)

**Comment by dennisweissmann** [comment]
Done :) Thanks again @Urkman!!
