### ISSUE TITLE
Add newly released devices

### ISSUE THREAD

**Issue by LaurentiuUngur** [dennisweissmann/DeviceKit#359]

**Comment by andrewhargreaves** [comment]
Agreed. Would be most appreciated.

**Comment by kushal211** [comment]
### Here's the **identifier** for the new iPhone devices:

**iPhone 15** 
`iPhone15,4`

**iPhone 15 Plus**
`iPhone15,5`

**iPhone 15 Pro**
`iPhone16,1`

**iPhone 15 Pro Max**
`iPhone16,2`

**Comment by furiosFast** [comment]
there is a ne PR: https://github.com/devicekit/DeviceKit/pull/360

**Comment by fandongtongxue** [comment]
+1

**Comment by HoustonDuane** [comment]
Apple actually doesn't call the new camera on iPhone 15 Pro Max "Periscope". It's still called "Telephoto camera".
<img width="1144" alt="image" src="https://github.com/devicekit/DeviceKit/assets/39131270/639de787-5c84-443e-af5d-dfbc444556d8">

**Comment by Zandor300** [comment]
Apple is using "telephoto camera" to describe the 5x lens on iPhone 15 Pro Max, so I think it is best to stick to that. I might be better to add extra functionality to DeviceKit to check how much zoom the device's telephoto camera is:

- iPhone 11 Pro: 2x
- iPhone 12 Pro (Max): 2x
- iPhone 13 Pro (Max): 3x
- iPhone 14 Pro (Max): 3x
- iPhone 15 Pro: 3x
- iPhone 15 Pro Max: 5x

But that is for another time, first need to add support for the devices.

**Comment by Zandor300** [comment]
Fixed by https://github.com/devicekit/DeviceKit/pull/360 through https://github.com/devicekit/DeviceKit/pull/362
