### ISSUE TITLE
xcodebuild: error Scheme DeviceKit-iOS is not currently configured for the build action

### ISSUE THREAD

**Issue by ejimenez93** [dennisweissmann/DeviceKit#46]
```
A shell task (/usr/bin/xcrun xcodebuild -project /Carthage/Checkouts/DeviceKit/DeviceKit.xcodeproj -scheme DeviceKit-iOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme DeviceKit-iOS is not currently configured for the build action.
```

Getting the error above after running a `carthage update`. Running `carthage update --platform iOS` does the same. Recently updated to XCode 8.0
My cartfile looks like this:

```
github "dennisweissmann/DeviceKit" ~> 1.0
```

**Comment by dennisweissmann** [comment]
Hi @ejimenez93, sorry for coming back to you so late. This might be related to https://github.com/Carthage/Carthage/issues/704 because the DeviceKit-iOS scheme does not exist anymore.
