### ISSUE TITLE
Add total and available disk space?

### ISSUE THREAD

**Issue by jamesbebbington** [dennisweissmann/DeviceKit#48]
Hey @dennisweissmann, would you consider adding info about the device's total and available disk space within scope for the library?

**Comment by dennisweissmann** [comment]
In the long term: definitely, in the short term: I don't have very much time recently :( but if someone provided a PR 😇 That'd be amazing! Maybe we can discuss the interface here so that it is consistent with the current implementation and everyone can join and then someone "just codes" it ;)
