### ISSUE TITLE
Installed the pod but what should I import? 

### ISSUE THREAD

**Issue by Agtsaras** [dennisweissmann/DeviceKit#53]
Hey there,

I'm trying to use this framework. I installed the pod (Swift 3.0) and now I'm trying to use the actual framework. When I write in my class file: let device = Device() it comes up with an error: "Use of an unresolved identifier "Device". So my question is how I can fix that?

**Comment by dennisweissmann** [comment]
Good question! Maybe I should add that to the Readme.

`import DeviceKit` should do.

**Comment by Agtsaras** [comment]
I tried that too but Xcode does not recognize it

**Comment by dennisweissmann** [comment]
Hm that's weird, can you try it in a clean project? Also make sure to open the workspace and not the project.

**Comment by Agtsaras** [comment]
it doesn't work in a clean project either... So weird. What could I possibly do wrong?

**Comment by dennisweissmann** [comment]
Sorry for coming back to you so late :( To be honest I have no idea why that wouldn't work, I confirmed locally that it actually *does* work :(

Steps:
1. Create an empty Xcode project (iOS, Single View App)
2. `cd` to the project dir
3. > pod init
4. add `pod 'DeviceKit', '~> 1.0'` under `# Pods for ProjectName`
5. > pod update
6. Open the workspace, go into the AppDelegate.swift file, add `import DeviceKit` and `let device = Device()`
7. Hit cmd+b -> Build successful

I'm really sorry, I have no idea what's going on on your machine :( Maybe make sure you're on the latest version of CocoaPods.
