### ISSUE TITLE
Missing iPhone 5C

### ISSUE THREAD

**Issue by LeonardoCardoso** [dennisweissmann/DeviceKit#54]
Missing iPhone 5C on `allPhones`:
[Device.swift#L262](https://github.com/dennisweissmann/DeviceKit/blob/ea64432c67dfca1d57f5b3109fcf813795dd837a/Source/Device.swift#L262)

**Comment by dennisweissmann** [comment]
😱 Daaaaamn! Awesome catch! Thank you so much!
