### ISSUE TITLE
isZoomed() Not working

### ISSUE THREAD

**Issue by kiwo12345** [dennisweissmann/DeviceKit#59]
I tried out the:

```
public var isZoomed: Bool {
    return UIScreen.main().scale < UIScreen.main().nativeScale
}
```

But it will never return true even if I have my device on zoomed.
My device is a real iphone 6 Plus/iOS 10.1

**Comment by kiwo12345** [comment]
Solution:

```
if(UIScreen.main.bounds.size.height == 667.0 && UIScreen.main.nativeScale < UIScreen.main.scale){
            print("iphone 6 plus")
        } else {
            print("none zoomed 6 plus")
        }

        if (UIScreen.main.bounds.size.height == 568.0 && UIScreen.main.nativeScale > UIScreen.main.scale) {
            print("zoomed iphone 6")
        } else {
            print("none zoomed")
        }
```

**Comment by dennisweissmann** [comment]
Hi @kiwo12345 , thank you so much for taking the time to report and actually finding a workaround for the issue :) 💯 However, I'm really not keen on hardcoding display heights :( Do you by any chance own an iPhone 5, SE, 6 or 7 (not the Plus version)? I only have the 6 Plus, 6s and 7 Plus (and an iPad Pro 12.9") for me to test I found the following:

```
print(UIScreen.main.nativeBounds)
print(UIScreen.main.bounds)
print(UIScreen.main.scale)
print(UIScreen.main.nativeScale)
```

iPhone 6/7 Plus ***not*** zoomed:
> (0.0, 0.0, 1080.0, 1920.0)
> (0.0, 0.0, 414.0, 736.0)
> 3.0
> 2.60869565217391

iPhone 6/7 Plus zoomed:
> (0.0, 0.0, 1080.0, 1920.0)
> (0.0, 0.0, 375.0, 667.0)
> 3.0
> 2.88

iPhone 6s ***not*** zoomed:
> (0.0, 0.0, 750.0, 1334.0)
> (0.0, 0.0, 375.0, 667.0)
> 2.0
> 2.0

iPhone 6s zoomed:
> (0.0, 0.0, 750.0, 1334.0)
> (0.0, 0.0, 320.0, 568.0)
> 2.0
> 2.34375

iPad Pro ***not*** zoomed:
> (0.0, 0.0, 2048.0, 2732.0)
> (0.0, 0.0, 1024.0, 1366.0)
> 2.0
> 2.0

iPad Pro zoomed:
> (0.0, 0.0, 2048.0, 2732.0)
> (0.0, 0.0, 768.0, 1024.0)
> 2.0
> 2.66666666666667

So it seems that for 2x devices we can say that if the native scale is larger than the current scale, the device is zoomed (which is what the current code in the framework does).
However, on 3x devices we need to differentiate. I'm currently thinking about something along those lines:

Pseudocode:
```
if Int(UIScreen.main.scale.rounded()) == 3 {
  // Plus-sized
  return UIScreen.main.nativeScale > 2.7
} else {
  return UIScreen.main.nativeScale > UIScreen.main.scale
}
```

which also includes a quite arbitrary hardcoded magic number :( I don't know what's better tbh, quick research online showed that both methods (yours and mine) are used.

**Comment by kiwo12345** [comment]
Hey @dennisweissmann I think I have a 5s and 5 SE that I can check if you want to. But yeah I agree,  not the best to have a hardcoded value : /

**Comment by vvit** [comment]
Hi guys, it seems the line
`return UIScreen.main.nativeScale > 2.7`
no longer works on the Simulator 12.4. Since the `UIScreen.main.nativeScale` is always 3 for non-zoomed display.
Does it support simulators?

I had to modify it to:
`return UIScreen.main.nativeScale > 2.7 && UIScreen.main.nativeScale < 3`

I can create a PR if needed. Thanks.
@dennisweissmann

**Comment by Zandor300** [comment]
@vvit 
Feel free to create a pull request for this issue.

(Dennis isn't working on this project anymore and he has handed it off to @denisenepraunig)

**Comment by vvit** [comment]
I see, thanks.
The problem is I need to check it on a real 'Plus' device which I don't have.

**Comment by Zandor300** [comment]
@vvit I will check on my old 6s Plus for you when you’ve prepared the PR. ;)

**Comment by vvit** [comment]
@Zandor300 thanks, pls check https://github.com/devicekit/DeviceKit/pull/195
