### ISSUE TITLE
Pod / Carthage

### ISSUE THREAD

**Issue by vCrespoP** [dennisweissmann/DeviceKit#6]
I think this is handy, you could make a pod to make it available easier and it should be simple as it's just one file without dependencies.

That would be nice for sure!

**Comment by dennisweissmann** [comment]
Thanks! Yeah I like that! This 'project' was initially thought to be a drop-in solution, but more and more people use it :):) Maybe I rename the whole project and make it a µ-framework (similar to Result). What do you think? I've never created a CocoaPods or Carthage file before, do you have any experience with that?

**Comment by vCrespoP** [comment]
Hallo!

Yes, it should be easy. Just follow their guide, it's 3 commands:
- Create the base project + structure automatically.
- Create the pod with a repository.
- Upload your code to the pod you created.

**Comment by dennisweissmann** [comment]
All right, I think everything is setup, I just need to publish it to cocoapods' trunk ... I tried that but that name is already taken ... Can you come up with a new one? :) I'm not very creative ...

**Comment by vCrespoP** [comment]
Uff...creativity hasn't kicked in today :P

I'm just gonna leave some random names that I can think of, or a mix of them:
Device + Info + Kit + Swifty + Denni + Handy

**Comment by dennisweissmann** [comment]
Awesome! I like DeviceKit pretty much :) Thanks! I'll give that a try tonight! :) (y) I have plans on extending the functionality to OS X so it will live up to its name some time in the future.

**Comment by dennisweissmann** [comment]
I've just renamed and published everything, I've tried it on 2 different machines, so everything should work out nicely (I hope) :) If you have any issues please let me know. I'll close this issue for now. Thanks again for using DeviceKit and making it even easier available to a broader audience. Thanks! :+1:

**Comment by vCrespoP** [comment]
Glad to read that!! 

Anytime :)
