### ISSUE TITLE
Crashes when searching for device that doesn't exist

### ISSUE THREAD

**Issue by kdawgwilk** [dennisweissmann/DeviceKit#60]
We were using a older version of the library in our app and hadn't updated it in awhile and then the iPhone 7 came out and we still didn't update...It couldn't find the identifier in the list and so it attempted to try and guess it was a Simulator which it wasn't and so it crashed because of the force unwrap [here](https://github.com/dennisweissmann/DeviceKit/blob/master/Source/Device.swift#L243) it would be nice if the case where a device doesn't exist in the list that it didn't crash but returned a unknown device or handled things in a better way

**Comment by kdawgwilk** [comment]
After looking at this some more I found that if you are looking up a Simulator identifier such a as `x86_64` but on a real device such as iPhone 7 Plus it will crash because it is looking for `getenv("SIMULATOR_MODEL_IDENTIFIER")` which doesn't exist on a real device!  So the library only supports looking up a Simulator identifier while running on a simulator.  It would prob be a good idea to handle this case and provide a default Simulator identifier such as `Simulator`

**Comment by dennisweissmann** [comment]
Fixed by #61 and #62, thank you so much for contributing! 💯🎉🙏
