### ISSUE TITLE
iPhone 5c is not under the Phone category

### ISSUE THREAD

**Issue by jacob-abraham** [dennisweissmann/DeviceKit#64]
When determining if the device is a phone, the iPhone 5c is not under it. It is a very simple fix. Just add iPhone 5c to the allPhones Bool

**Comment by dennisweissmann** [comment]
Hey @jacob-abraham,

Thanks for the report. This was already fixed on master with fa6c2180979669487376156fa0aaf6b2f10f0a16 but I haven't released a new version since then. I'll try to do that today!
