### ISSUE TITLE
Get device type in terms of GSM or CDMA

### ISSUE THREAD

**Issue by ankitgoyalgithub** [dennisweissmann/DeviceKit#72]
Can we extend this to get the type of the device as well say whether the device is GSM or CDMA or supports both ?

**Comment by dennisweissmann** [comment]
Sure, I'm currently busy with other stuff though, do you know if there's a public way to check that? If not I'll look into it (probably around end of May) :)

**Comment by ankitgoyalgithub** [comment]
Awesome. I will also try to figure that out. Seems no public way to do right now.

**Comment by dennisweissmann** [comment]
Perfect thanks! 🙏 

We/I have to figure out a way (e.g. a compile time switch) to opt-in those non-AppStore-secure parts.

**Comment by dennisweissmann** [comment]
Hey @ankitgoyalgithub , any news on this?

**Comment by dennisweissmann** [comment]
Closed due to inactivity
