### ISSUE TITLE
Xcode 8.3.3 - Swift Language version error

### ISSUE THREAD

**Issue by hunterleebrown** [dennisweissmann/DeviceKit#83]
I'm getting this when using Carthage, or building master directly from a git clone: 

Check dependencies

“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

---

I think the project file for master is defaulting to Swift 4.0, where it should be changed to  Swift 3.0.  Should I be using the "swift-3" branch?

**Comment by hunterleebrown** [comment]
I can use the "swift-3" branch....

**Comment by dennisweissmann** [comment]
Yeah sorry, swift-3 is currently the stable Swift 3 branch. I should probably note that down somewhere ... sorry for the trouble!
