### ISSUE TITLE
"Module compiled with swift 4.0 cannot be imported in swift 3.1" error on build

### ISSUE THREAD

**Issue by Domsware** [dennisweissmann/DeviceKit#84]
Yesterday I tried Xcode9 beta. Now I want to go back using Xcode 8 but I faced this error on project build for DeviceKit and only for DeviceKit:

`Module compiled with swift 4.0 cannot be imported in swift 3.1`

The framework installation is made by Carthage. Building DeviceKit project on Xcode 8 works fine. But not on my project. I've tried a lot of things from deleting all Carthage and rebuild all, cleaning project, removing Derived Data... But the problem is still here. And only on DeviceKit.

So I wonder if there is some configuration in DeviceKit to be made to solve it.

**Comment by dennisweissmann** [comment]
I *think* that is because DeviceKit uses the new build system and does not use the normal DerivedData folder (at least on my machine, I'm not sure whether this is a local/user or shared setting ... You may wanna try deleting any "Derived Data" folder inside DeviceKit's root dir ... Does that help?

**Comment by Domsware** [comment]
I found the problem: it was related to Carthage. See the answer on [StackOverflow](https://stackoverflow.com/q/45450781/540780).
