### ISSUE TITLE
Crash on ContiguousArrayBuffer.init(_uninitializedCount:minimumCapacity:)

### ISSUE THREAD

**Issue by lowki93** [dennisweissmann/DeviceKit#85]
Hello, 
I've a crash when i use `device.isSimulator`
You can see the crash log 
[com.aircall.aircall_issue_1754_crash_a9c6a42051ee437aacd6c697e0e2d8c1_88e7791d791311e7817856847afe9799_0_v2.txt](https://github.com/dennisweissmann/DeviceKit/files/1200961/com.aircall.aircall_issue_1754_crash_a9c6a42051ee437aacd6c697e0e2d8c1_88e7791d791311e7817856847afe9799_0_v2.txt)

Do you have an idea ?

**Comment by dennisweissmann** [comment]
:O I'm sorry that this happened :( Which version of DeviceKit do you use?

**Comment by lowki93** [comment]
on the lastest version

**Comment by dennisweissmann** [comment]
Darn :( Can this be problem: https://stackoverflow.com/questions/33426618/swift-crash-array-allocatebufferuninitialized ?

**Comment by dennisweissmann** [comment]
Do you still see a crash or can I close this issue?

**Comment by lowki93** [comment]
i'm on vacation. I check Monday morning :)

**Comment by dennisweissmann** [comment]
Sorry! Take your time and enjoy your holidays :)

**Comment by dennisweissmann** [comment]
Any news here @lowki93 ?

**Comment by lowki93** [comment]
i can't reproduce this bug ...
I close the issues. If i have some news, i reopen it ;)
