### ISSUE TITLE
Safer logic in `Device().isPad`

### ISSUE THREAD

**Issue by sovata8** [dennisweissmann/DeviceKit#88]
Newly introduced Apple devices might report incorrectly from `Device().isPad`.

In my case, I had not updated DeviceKit and the newly introduced `iPad (7,4)` was not being handled properly.

If developers are not careful, this might cause critical bugs.

 I think it might be safer if the logic is such that there is at least a 'fallback' for APIs such as `isPad`. For example if the device lookup (in `Device.swift.gyb
`) fails, the `isPad` logic falls back to native Apple APIs  (e.g. `userInterfaceIdiom`).

**Comment by dennisweissmann** [comment]
Hi, that’s a very good point! I had that on my mind quite a while and wanted to implement it by testing the prefix of the device identifier ... yours is even more future-proof I think 🤔

Anyways, it’s a important issue that needs to be fixed, thanks for writing it down!

**Comment by dennisweissmann** [comment]
Resolved in #91 Thanks @sovata8 for reporting it!
