### ISSUE TITLE
Add iPhone8, iPhone8+ and iPhoneX?

### ISSUE THREAD

**Issue by Urkman** [dennisweissmann/DeviceKit#89]
Any plans to add the new iPhones?

**Comment by walsht** [comment]
+1

**Comment by dennisweissmann** [comment]
Thanks @walsht for taking care so fast! This is awesome :)

**Comment by Urkman** [comment]
Can you merge the pull request and make a new release?

**Comment by dennisweissmann** [comment]
Yeah sure, once the SwiftLint warning is fixed I can merge it.

**Comment by dennisweissmann** [comment]
closed by #90
