### ISSUE TITLE
Switch must be exhaustive, consider adding a default clause

### ISSUE THREAD

**Issue by gloryluu** [dennisweissmann/DeviceKit#9]
I got it in Device.swift, line 211. Any solution?

**Comment by dennisweissmann** [comment]
😱 That is weird! On my machines builds are passing and so are all tests. Can you explain what you did and can you paste the init() method here? Thanks!

**Comment by gloryluu** [comment]
Very sorry @dennisweissmann. I didnt notice that you switched to DeviceKit. The problem happens with the obsolete Device.swift one, not with the new DeviceKit.
I changed my pod to DeviceKit and the problem is gone.

**Comment by dennisweissmann** [comment]
Ah perfect! No problem :) Glad it is working now :+1:
