### ISSUE TITLE
Install from Pod and new Realease

### ISSUE THREAD

**Issue by Urkman** [dennisweissmann/DeviceKit#92]
When I install the master branch from pods, it is not working:
pod 'DeviceKit', :git => 'https://github.com/dennisweissmann/DeviceKit', :branch => 'master'

Is it possible, that you make a new release asap?

**Comment by dennisweissmann** [comment]
I'm at it :) but it's weird that it's not working from master ...

**Comment by Urkman** [comment]
When I try to install from master, I get an empty DeviceKit Folder...

**Comment by dennisweissmann** [comment]
Darn! thanks for trying that! Seems that didn't work since we generate the actual source file using gyb. Trying to resolve, hope I have a solution in #93

**Comment by dennisweissmann** [comment]
Okay this is fixed with #93 , it's not nice (I have to include the generated file in the repository because CocoaPods does not support custom build phases :( ) but it works

**Comment by Urkman** [comment]
hmmm... Perhaps there is a problem on my side, but:
Here its no iPhone8, iPhone8 Plus and iPhone X :
https://github.com/dennisweissmann/DeviceKit/blob/master/Source/Device.generated.swift

:(

**Comment by dennisweissmann** [comment]
:O That's why I hate that approach :/ Thanks for reminding me! Working on it

**Comment by dennisweissmann** [comment]
@Urkman This should hopefully be fixed in 1.3.1 ... thanks again for taking the time to open an issue :) And thanks for using DeviceKit :)

**Comment by Urkman** [comment]
@dennisweissmann Yes, look good now :) Installs also from master branch...

Thanks for all your work 👍

**Comment by dennisweissmann** [comment]
Perfect :) You're welcome!
