### ISSUE TITLE
Carthage won't build DeviceKit.framework

### ISSUE THREAD

**Issue by rzulkoski** [dennisweissmann/DeviceKit#96]
Running `carthage update --platform iOS` results in the following error:

`*** Building scheme "DeviceKit" in DeviceKit.xcodeproj
Failed to write to /Users/ryan/Developer/storefront-ios/Carthage/Build/iOS/DeviceKit.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “DeviceKit.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/ryan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/DeviceKit/1.3.0/Build/Products/Release-iphoneos/DeviceKit.framework, NSFilePath=/Users/ryan/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/DeviceKit/1.3.0/Build/Products/Release-iphoneos/DeviceKit.framework, NSUnderlyingError=0x7fdbf3c1cb40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

Versions:
macOS Sierra 10.12.6
Xcode 9.0 (9A235)
Carthage 0.25.0
DeviceKit 1.3.0 and 1.3.1

**Comment by walsht** [comment]
+1

**Comment by hunterleebrown** [comment]
+1

**Comment by qcasxy** [comment]
+1

**Comment by kenshincui** [comment]
+1

**Comment by Ashok28** [comment]
+1

**Comment by dennisweissmann** [comment]
Does anyone know how to fix this? Is this a Carthage issue? When I run `xcodebuild -scheme DeviceKit -project ./DeviceKit.xcodeproj/ build` it works fine ...

**Comment by dennisweissmann** [comment]
Okay, it seems it is build system related: https://github.com/Carthage/Carthage/issues/2026

That's bad and since you all don't wanna wait for a fix I'll change it to the old build system ... sorry for the inconvenience!

**Comment by rzulkoski** [comment]
Thanks Dennis!

**Comment by dennisweissmann** [comment]
This is fixed in 1.3.2 (at least for me locally, would be great if someone could confirm that before I close the issue :) )

**Comment by walsht** [comment]
Verified... fixed

**Comment by dennisweissmann** [comment]
Thank you for verifying Tim and thank you all for using DeviceKit 🙏
