### ISSUE TITLE
LLVM Instrumentation

### ISSUE THREAD

**Issue by walsht** [dennisweissmann/DeviceKit#98]
Got an invalid binary when pushing to Apple because your framework has "Gather coverage date" checked on your test target. Please update.
https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675
https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675-CH1-INSPECT

Same issue I fixed for Agrume https://github.com/JanGorman/Agrume/issues/61

I will make a PR shortly.

**Comment by dennisweissmann** [comment]
Thanks Tim :)

As far as I can tell though, the underlying issue is that Carthage does not "archive" but "build", is that right?

From https://developer.apple.com/library/content/qa/qa1964/_index.html#//apple_ref/doc/uid/DTS40017675

> Starting with Xcode 9, if the Gather coverage data option is enabled on the scheme, regular builds for the Run action will also build with code coverage instrumentation, but archive builds will not. If your app's build uses scripts to generate or move build products into place, you need to ensure these scripts only use archived build products when receiving the archive build action; otherwise, build products created with the build action will contain instrumentation and result in a rejection from the App Store.

Sorry for the trouble and the delay of your app being accepted :(

**Comment by walsht** [comment]
I don't think it is a Carthage issue because this would affect other ways to that use your framework

**Comment by dennisweissmann** [comment]
Hm 🤔 I'll look into that.

Thanks for providing a fix :)

Release is 1.3.3 https://github.com/dennisweissmann/DeviceKit/releases/tag/1.3.3
